imports:
  - { resource: easyadmin/ }

easy_admin:
  design:
    menu:
      -
        label: 'Intl'
        priority: 0
        roles: ['ROLE_INTL']
        children:
            - { entity: 'Translation', icon: 'globe' }
            - { label: 'Trans. Import/Export', route: 'krg_intl_admin_import', icon: 'upload' }
