easy_admin:
    design:
        menu:
            -
                label: 'Intl'
                group: 'Intl'
                priority: 0
                roles: ['ROLE_INTL']
                icon: 'globe'
                children:
                    - { label: 'Trans. Import/Export', route: 'krg_intl_admin_import', icon: 'upload' }
