services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locales: '%krg_intl_locales%'
            $defaultLocale: '%kernel.default_locale%'
            $translatableListener: '@stof_doctrine_extensions.listener.translatable'

    KRG\IntlBundle\:
        resource: '../../*'
        public: true
        exclude: '../../{Entity,Repository,Tests}'

    KRG\IntlBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]
