services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locales: '%krg_intl_locales%'
            $defaultLocale: '%kernel.default_locale%'
            $translatableListener: '@gedmo.listener.translatable'

    KRG\IntlBundle\:
        resource: '../../*'
        public: true
        exclude: '../../{Entity,Repository,Tests}'

    KRG\IntlBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

#    krg.translatable.listener:
#        class: Gedmo\Translatable\TranslatableListener
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ '@annotation_reader' ] ]
#            - [ setDefaultLocale, [ '%kernel.default_locale%' ] ]
#            - [ setTranslationFallback, [ true ] ]
            # - [ setPersistDefaultLocaleTranslation, [ true ]]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ '%locale%' ] ]
            - [ setTranslationFallback, [ true ] ]