easy_admin:
    entities:
        Translation:
            class: 'KRG\IntlBundle\Entity\TranslationInterface'
            disabled_actions: ['new']
            list:
                title: 'Translation'
                dql_filter: "entity.objectClass = '_source'"
                fields:
                    - id
                    - locale
                    -
                        property: content
                        domain: 'null'
                    -
                        property: foreignTextKey
                        domain: 'null'
                    - { property: 'objectClass'}
                    - { property: 'field'}
            search:
                title:  '<i class="fa fa-search"></i> Traductions'
            form:
                fields:
                    - { type: 'group' }
                    - { property: 'locale', type_options: { disabled: true } }
                    - { property: 'field', type_options: { disabled: true } }
                    - { property: 'foreignTextKey', type_options: { disabled: true } }
                    - { property: 'content', type: 'textarea', type_options: { attr: { rows: 10 }} }
